
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src


COPY ["ApiGateaway.csproj", "./"]
RUN dotnet restore "ApiGateaway.csproj"

COPY . .
RUN dotnet publish "ApiGateaway.csproj" -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "ApiGateaway.dll"]
